name: Sync dify images to ACR(Alibaba Cloud Container Registry)

on:
  workflow_dispatch:

env:
  ACR_REGISTRY: registry.cn-hangzhou.aliyuncs.com

jobs:
  pull-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to the ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 登录 GitHub Container Registry（使用 PAT）
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}   # 注意这里改为新 secret

      - name: Pull ghcr.io/yikart/aitoearn-channel:latest image from Docker Hub
        run: docker pull ghcr.io/yikart/aitoearn-channel:latest

      - name: Tag ghcr.io/yikart/aitoearn-channel:latest image for ACR
        run: docker tag ghcr.io/yikart/aitoearn-channel:latest ${{ env.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/aitoearn-channel:latest

      - name: Push ghcr.io/yikart/aitoearn-channel:latest image to Aliyun Registry
        run: docker push ${{ env.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/aitoearn-channel:latest
